In [ ]:
import pandas as pd

In [5]:
pwd

'C:\\Users\\Alan\\FYP\\testing'

In [4]:
data = pd.read_csv('..\\dataset\\fer2013.csv')

In [6]:
data.head()

   emotion                                             pixels     Usage
0        0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...  Training
1        0  151 150 147 155 148 133 111 140 170 174 182 15...  Training
2        2  231 212 156 164 174 138 161 173 182 200 106 38...  Training
3        4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...  Training
4        6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...  Training

In [11]:
data

       emotion                                             pixels        Usage
0            0  70 80 82 72 58 58 60 63 54 58 60 48 89 115 121...     Training
1            0  151 150 147 155 148 133 111 140 170 174 182 15...     Training
2            2  231 212 156 164 174 138 161 173 182 200 106 38...     Training
3            4  24 32 36 30 32 23 19 20 30 41 21 22 32 34 21 1...     Training
4            6  4 0 0 0 0 0 0 0 0 0 0 0 3 15 23 28 48 50 58 84...     Training
5            2  55 55 55 55 55 54 60 68 54 85 151 163 170 179 ...     Training
6            4  20 17 19 21 25 38 42 42 46 54 56 62 63 66 82 1...     Training
7            3  77 78 79 79 78 75 60 55 47 48 58 73 77 79 57 5...     Training
8            3  85 84 90 121 101 102 133 153 153 169 177 189 1...     Training
9            2  255 254 255 254 254 179 122 107 95 124 149 150...     Training
10           0  30 24 21 23 25 25 49 67 84 103 120 125 130 139...     Training
11           6  39 75 78 58 58 45 49 48 103 156 81 45 41 38 49...     Training
12           6  219 213 206 202 209 217 216 215 219 218 223 23...     Training
13           6  148 144 130 129 119 122 129 131 139 153 140 12...     Training
14           3  4 2 13 41 56 62 67 87 95 62 65 70 80 107 127 1...     Training
15           5  107 107 109 109 109 109 110 101 123 140 144 14...     Training
16           3  14 14 18 28 27 22 21 30 42 61 77 86 88 95 100 ...     Training
17           2  255 255 255 255 255 255 255 255 255 255 255 25...     Training
18           6  134 124 167 180 197 194 203 210 204 203 209 20...     Training
19           4  219 192 179 148 208 254 192 98 121 103 145 185...     Training
20           4  1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 7 12 23 45 38 ...     Training
21           2  174 51 37 37 38 41 22 25 22 24 35 51 70 83 98 ...     Training
22           0  123 125 124 142 209 226 234 236 231 232 235 22...     Training
23           0  8 9 14 21 26 32 37 46 52 62 72 70 71 73 76 83 ...     Training
24           3  252 250 246 229 182 140 98 72 53 44 67 95 95 8...     Training
25           3  224 227 219 217 215 210 187 177 189 200 206 21...     Training
26           5  162 200 187 180 197 198 196 192 176 152 136 11...     Training
27           0  236 230 225 226 228 209 199 193 196 211 199 19...     Training
28           3  210 210 210 210 211 207 147 103 68 60 47 70 12...     Training
29           5  50 44 74 141 187 187 169 113 80 128 181 172 76...     Training
...        ...                                                ...          ...
35857        5  253 255 229 150 89 61 54 60 55 49 61 50 56 45 ...  PrivateTest
35858        4  11 11 11 13 20 27 38 41 38 34 20 13 10 39 85 1...  PrivateTest
35859        4  11 13 16 27 24 26 89 161 190 197 201 206 210 2...  PrivateTest
35860        3  27 42 62 91 112 118 122 123 119 124 129 131 13...  PrivateTest
35861        6  233 232 208 188 194 179 177 167 157 180 185 19...  PrivateTest
35862        2  73 54 63 76 82 71 67 69 73 72 92 98 117 119 14...  PrivateTest
35863        5  196 196 197 197 198 198 198 196 176 148 122 10...  PrivateTest
35864        4  68 59 65 78 118 131 137 141 142 135 135 137 13...  PrivateTest
35865        3  102 109 109 106 104 107 112 109 116 119 117 12...  PrivateTest
35866        6  87 82 59 61 72 102 143 130 90 95 143 173 146 1...  PrivateTest
35867        3  198 198 197 196 196 197 196 196 196 195 196 18...  PrivateTest
35868        2  204 209 215 218 214 214 214 217 205 175 170 16...  PrivateTest
35869        3  217 220 222 223 223 224 225 223 223 225 223 22...  PrivateTest
35870        2  6 8 4 5 30 48 61 70 76 79 98 117 130 137 143 1...  PrivateTest
35871        6  112 102 98 89 98 133 164 185 180 179 185 169 1...  PrivateTest
35872        5  131 159 90 59 10 0 1 1 1 0 1 1 0 0 2 2 5 7 9 1...  PrivateTest
35873        4  54 57 77 122 121 76 73 80 58 22 26 27 35 41 66...  PrivateTest
35874        5  43 43 51 73 94 97 102 95 99 107 126 144 154 17...  PrivateTest
35875        5  248 251 239 144 102 95 82 77 91 138 153 145 14...  PrivateTest
35876        6  29 29 27 31 49 56 29 19 22 20 34 43 55 71 85 9...  PrivateTest
35877        6  139 143 145 154 159 168 176 181 190 191 195 19...  PrivateTest
35878        3  0 39 81 80 104 97 51 64 68 46 41 67 53 68 70 5...  PrivateTest
35879        2  0 0 6 16 19 31 47 18 26 19 17 8 15 3 4 2 14 20...  PrivateTest
35880        2  164 172 175 171 172 173 178 181 188 192 197 20...  PrivateTest
35881        0  181 177 176 156 178 144 136 132 122 107 131 16...  PrivateTest
35882        6  50 36 17 22 23 29 33 39 34 37 37 37 39 43 48 5...  PrivateTest
35883        3  178 174 172 173 181 188 191 194 196 199 200 20...  PrivateTest
35884        0  17 17 16 23 28 22 19 17 25 26 20 24 31 19 27 9...  PrivateTest
35885        3  30 28 28 29 31 30 42 68 79 81 77 67 67 71 63 6...  PrivateTest
35886        2  19 13 14 12 13 16 21 33 50 57 71 84 97 108 122...  PrivateTest

[35887 rows x 3 columns]

In [10]:
data_emotion = data.groupby('emotion')
data_emotion.count()

         pixels  Usage
emotion
0          4953   4953
1           547    547
2          5121   5121
3          8989   8989
4          6077   6077
5          4002   4002
6          6198   6198

In [14]:
data_usage = data.groupby('Usage')
data_usage.count()

             emotion  pixels
Usage
PrivateTest     3589    3589
PublicTest      3589    3589
Training       28709   28709

In [18]:
import sys
sys.path.insert(0, '../')

from helper import load_dataset
faces, emotions = load_dataset()

..\helper.py:21: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  emotions = pd.get_dummies(data['emotion']).as_matrix() # convert emotion values into dummy variables

In [25]:
print(faces)

[[[[ 70.]
   [ 76.]
   [ 81.]
   ...
   [ 46.]
   [ 42.]
   [ 41.]]

  [[ 67.]
   [ 68.]
   [ 68.]
   ...
   [ 51.]
   [ 46.]
   [ 43.]]

  [[ 59.]
   [ 56.]
   [ 55.]
   ...
   [ 53.]
   [ 50.]
   [ 45.]]

  ...

  [[ 82.]
   [ 78.]
   [ 72.]
   ...
   [ 75.]
   [ 57.]
   [ 45.]]

  [[ 77.]
   [ 78.]
   [ 79.]
   ...
   [ 92.]
   [ 75.]
   [ 60.]]

  [[ 77.]
   [ 74.]
   [ 76.]
   ...
   [108.]
   [ 99.]
   [ 82.]]]


 [[[151.]
   [150.]
   [149.]
   ...
   [136.]
   [132.]
   [120.]]

  [[151.]
   [150.]
   [149.]
   ...
   [134.]
   [137.]
   [131.]]

  [[151.]
   [150.]
   [150.]
   ...
   [128.]
   [136.]
   [140.]]

  ...

  [[188.]
   [188.]
   [180.]
   ...
   [184.]
   [184.]
   [187.]]

  [[187.]
   [186.]
   [188.]
   ...
   [185.]
   [184.]
   [186.]]

  [[186.]
   [185.]
   [184.]
   ...
   [187.]
   [183.]
   [184.]]]


 [[[231.]
   [219.]
   [191.]
   ...
   [ 33.]
   [ 23.]
   [ 16.]]

  [[230.]
   [204.]
   [175.]
   ...
   [ 33.]
   [ 29.]
   [ 23.]]

  [[223.]
   [189.]
   [162.]
   ...
   [ 29.]
   [ 29.]
   [ 27.]]

  ...

  [[244.]
   [247.]
   [249.]
   ...
   [ 91.]
   [123.]
   [156.]]

  [[248.]
   [249.]
   [250.]
   ...
   [ 97.]
   [126.]
   [158.]]

  [[250.]
   [251.]
   [251.]
   ...
   [102.]
   [126.]
   [152.]]]


 ...


 [[[ 17.]
   [ 17.]
   [ 17.]
   ...
   [102.]
   [163.]
   [245.]]

  [[ 18.]
   [ 17.]
   [ 16.]
   ...
   [116.]
   [173.]
   [250.]]

  [[ 18.]
   [ 17.]
   [ 16.]
   ...
   [131.]
   [184.]
   [254.]]

  ...

  [[  5.]
   [ 13.]
   [ 28.]
   ...
   [177.]
   [177.]
   [180.]]

  [[ 11.]
   [ 14.]
   [ 23.]
   ...
   [161.]
   [155.]
   [152.]]

  [[ 20.]
   [ 17.]
   [ 17.]
   ...
   [141.]
   [125.]
   [113.]]]


 [[[ 30.]
   [ 29.]
   [ 28.]
   ...
   [ 54.]
   [ 48.]
   [ 44.]]

  [[ 30.]
   [ 28.]
   [ 28.]
   ...
   [ 55.]
   [ 47.]
   [ 42.]]

  [[ 30.]
   [ 28.]
   [ 28.]
   ...
   [ 56.]
   [ 47.]
   [ 39.]]

  ...

  [[103.]
   [105.]
   [107.]
   ...
   [ 32.]
   [ 30.]
   [ 29.]]

  [[ 99.]
   [100.]
   [103.]
   ...
   [ 32.]
   [ 30.]
   [ 29.]]

  [[ 93.]
   [ 95.]
   [ 97.]
   ...
   [ 32.]
   [ 29.]
   [ 28.]]]


 [[[ 19.]
   [ 15.]
   [ 13.]
   ...
   [100.]
   [ 91.]
   [ 86.]]

  [[ 17.]
   [ 16.]
   [ 15.]
   ...
   [ 99.]
   [ 92.]
   [ 89.]]

  [[ 14.]
   [ 14.]
   [ 14.]
   ...
   [ 97.]
   [ 93.]
   [ 92.]]

  ...

  [[ 16.]
   [ 15.]
   [ 14.]
   ...
   [118.]
   [140.]
   [156.]]

  [[ 15.]
   [ 15.]
   [ 14.]
   ...
   [169.]
   [187.]
   [195.]]

  [[ 16.]
   [ 15.]
   [ 13.]
   ...
   [195.]
   [200.]
   [201.]]]]

In [24]:
print(emotions)

[[1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 1 ... 0 0 0]]

In [26]:
from helper import preprocess_input
faces = preprocess_input(faces)
print(faces)

[[[[-0.45098037]
   [-0.40392154]
   [-0.36470586]
   ...
   [-0.6392157 ]
   [-0.67058825]
   [-0.6784314 ]]

  [[-0.47450978]
   [-0.46666664]
   [-0.46666664]
   ...
   [-0.6       ]
   [-0.6392157 ]
   [-0.6627451 ]]

  [[-0.5372549 ]
   [-0.56078434]
   [-0.5686275 ]
   ...
   [-0.58431375]
   [-0.60784316]
   [-0.64705884]]

  ...

  [[-0.35686272]
   [-0.38823527]
   [-0.4352941 ]
   ...
   [-0.41176468]
   [-0.5529412 ]
   [-0.64705884]]

  [[-0.3960784 ]
   [-0.38823527]
   [-0.38039213]
   ...
   [-0.27843136]
   [-0.41176468]
   [-0.5294118 ]]

  [[-0.3960784 ]
   [-0.41960782]
   [-0.40392154]
   ...
   [-0.15294117]
   [-0.2235294 ]
   [-0.35686272]]]


 [[[ 0.18431377]
   [ 0.17647064]
   [ 0.1686275 ]
   ...
   [ 0.06666672]
   [ 0.03529418]
   [-0.05882353]]

  [[ 0.18431377]
   [ 0.17647064]
   [ 0.1686275 ]
   ...
   [ 0.05098045]
   [ 0.07450986]
   [ 0.02745104]]

  [[ 0.18431377]
   [ 0.17647064]
   [ 0.17647064]
   ...
   [ 0.00392163]
   [ 0.06666672]
   [ 0.09803927]]

  ...

  [[ 0.47450984]
   [ 0.47450984]
   [ 0.41176474]
   ...
   [ 0.4431373 ]
   [ 0.4431373 ]
   [ 0.4666667 ]]

  [[ 0.4666667 ]
   [ 0.45882356]
   [ 0.47450984]
   ...
   [ 0.45098042]
   [ 0.4431373 ]
   [ 0.45882356]]

  [[ 0.45882356]
   [ 0.45098042]
   [ 0.4431373 ]
   ...
   [ 0.4666667 ]
   [ 0.43529415]
   [ 0.4431373 ]]]


 [[[ 0.8117647 ]
   [ 0.7176471 ]
   [ 0.49803925]
   ...
   [-0.7411765 ]
   [-0.81960785]
   [-0.8745098 ]]

  [[ 0.8039216 ]
   [ 0.6       ]
   [ 0.37254906]
   ...
   [-0.7411765 ]
   [-0.77254903]
   [-0.81960785]]

  [[ 0.7490196 ]
   [ 0.48235297]
   [ 0.27058828]
   ...
   [-0.77254903]
   [-0.77254903]
   [-0.7882353 ]]

  ...

  [[ 0.9137255 ]
   [ 0.9372549 ]
   [ 0.9529412 ]
   ...
   [-0.2862745 ]
   [-0.03529412]
   [ 0.22352946]]

  [[ 0.94509804]
   [ 0.9529412 ]
   [ 0.9607843 ]
   ...
   [-0.23921567]
   [-0.01176471]
   [ 0.23921573]]

  [[ 0.9607843 ]
   [ 0.96862745]
   [ 0.96862745]
   ...
   [-0.19999999]
   [-0.01176471]
   [ 0.19215691]]]


 ...


 [[[-0.8666667 ]
   [-0.8666667 ]
   [-0.8666667 ]
   ...
   [-0.19999999]
   [ 0.27843142]
   [ 0.92156863]]

  [[-0.85882354]
   [-0.8666667 ]
   [-0.8745098 ]
   ...
   [-0.09019607]
   [ 0.35686278]
   [ 0.9607843 ]]

  [[-0.85882354]
   [-0.8666667 ]
   [-0.8745098 ]
   ...
   [ 0.02745104]
   [ 0.4431373 ]
   [ 0.99215686]]

  ...

  [[-0.9607843 ]
   [-0.8980392 ]
   [-0.78039217]
   ...
   [ 0.38823533]
   [ 0.38823533]
   [ 0.41176474]]

  [[-0.9137255 ]
   [-0.8901961 ]
   [-0.81960785]
   ...
   [ 0.26274514]
   [ 0.21568632]
   [ 0.19215691]]

  [[-0.84313726]
   [-0.8666667 ]
   [-0.8666667 ]
   ...
   [ 0.10588241]
   [-0.01960784]
   [-0.11372548]]]


 [[[-0.7647059 ]
   [-0.77254903]
   [-0.78039217]
   ...
   [-0.5764706 ]
   [-0.62352943]
   [-0.654902  ]]

  [[-0.7647059 ]
   [-0.78039217]
   [-0.78039217]
   ...
   [-0.5686275 ]
   [-0.6313726 ]
   [-0.67058825]]

  [[-0.7647059 ]
   [-0.78039217]
   [-0.78039217]
   ...
   [-0.56078434]
   [-0.6313726 ]
   [-0.69411767]]

  ...

  [[-0.19215685]
   [-0.17647058]
   [-0.1607843 ]
   ...
   [-0.7490196 ]
   [-0.7647059 ]
   [-0.77254903]]

  [[-0.2235294 ]
   [-0.21568626]
   [-0.19215685]
   ...
   [-0.7490196 ]
   [-0.7647059 ]
   [-0.77254903]]

  [[-0.27058822]
   [-0.25490195]
   [-0.23921567]
   ...
   [-0.7490196 ]
   [-0.77254903]
   [-0.78039217]]]


 [[[-0.8509804 ]
   [-0.88235295]
   [-0.8980392 ]
   ...
   [-0.21568626]
   [-0.2862745 ]
   [-0.32549018]]

  [[-0.8666667 ]
   [-0.8745098 ]
   [-0.88235295]
   ...
   [-0.2235294 ]
   [-0.27843136]
   [-0.30196077]]

  [[-0.8901961 ]
   [-0.8901961 ]
   [-0.8901961 ]
   ...
   [-0.23921567]
   [-0.27058822]
   [-0.27843136]]

  ...

  [[-0.8745098 ]
   [-0.88235295]
   [-0.8901961 ]
   ...
   [-0.0745098 ]
   [ 0.09803927]
   [ 0.22352946]]

  [[-0.88235295]
   [-0.88235295]
   [-0.8901961 ]
   ...
   [ 0.32549024]
   [ 0.4666667 ]
   [ 0.5294118 ]]

  [[-0.8745098 ]
   [-0.88235295]
   [-0.8980392 ]
   ...
   [ 0.5294118 ]
   [ 0.5686275 ]
   [ 0.5764706 ]]]]

In [34]:
from helper import split_data
train_data, val_data = split_data(faces, emotions, validation_split=0.2)

SyntaxError: invalid syntax (<ipython-input-34-968d716588ba>, line 3)